#!/usr/bin/env python3

import sys, os
from helpers import get_user_timeline
from analyzer import Analyzer
from nltk.tokenize import TweetTokenizer
from termcolor import colored

def main():
	if len(sys.argv) != 2:
		sys.exit("Usage: tweet twitterUsername")

	twitter_handle = sys.argv[1]

	positives = os.path.join(sys.path[0], "positive-words.txt")
	negatives = os.path.join(sys.path[0], "negative-words.txt")
	analyzer = Analyzer(positives, negatives)

	tweets = get_user_timeline(twitter_handle, 50)
	twt_tokenizer = TweetTokenizer()
	for tweet in tweets:
		tokens = twt_tokenizer.tokenize(tweet)
		#print(tokens)
		sentiment_counter = 0
		for token in tokens:
			sentiment_counter += analyzer.analyze(token)
		if sentiment_counter > 0:
			color = "green"
		elif sentiment_counter < 0:
			color = "red"
		else:
			color = "yellow"
		print(colored(tweet, color))
		print(sentiment_counter)

if __name__ == "__main__":
	main()